name: Build APK - La Tasa de Oro (APK EXACTO)

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CI: "true"
      FLET_CLI_NO_ASK: "true"
      PUB_NON_INTERACTIVE: "1"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Flet
        run: |
          python -m pip install --upgrade pip
          pip install flet==0.84.0

      - name: Build APK
        run: |
          yes | flet build apk

      - name: Extraer el APK Real
        run: |
          # Buscamos SOLO en la carpeta final que genera Flet y tomamos el primer resultado
          APK_REAL=$(find ./build/apk -type f -name "*.apk" | head -n 1)
          
          echo "========================================="
          echo "APK REAL ENCONTRADO EN: $APK_REAL"
          echo "========================================="
          
          # Mostrar su tamaño real en consola
          ls -lh "$APK_REAL"
          
          # Crear carpeta limpia y copiar SOLO ese archivo
          mkdir dist
          cp "$APK_REAL" dist/LaTasaDeOro.apk

      - name: Upload APK LIMPIO
        uses: actions/upload-artifact@v4
        with:
          name: apk-limpio-final
          path: dist/LaTasaDeOro.apk
